name: Test & Lint

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    services:
      netbox:
        image: netboxcommunity/netbox:latest
        env:
          SKIP_SUPERUSER: true
        ports:
          - 8000:8080

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Run ruff linter
        run: uv run ruff check .

      - name: Run ruff formatter
        run: uv run ruff format --check .

      - name: Run pytest
        run: uv run pytest -v
        env:
          NETBOX_URL: http://localhost:8000
          NETBOX_TOKEN: ${{ secrets.NETBOX_TOKEN }}
